- name: 'Provision Image'
  hosts: localhost
  become: true
  tasks:
    - shell:
        cmd: apt -y upgrade
    - shell:
        cmd: cloud-init clean --machine-id
    - pause:
        seconds: 30
#    - name: Remove Packer's cloud init
#      file:
#        path: /etc/cloud/cloud.cfg.d/99-installer.cfg
#        state: absent
#
